name: Build DDP and run tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DDPPATH: /home/runner/work/Kompilierer/Kompilierer/build/DDP/

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
          go-version: "1.20.0"
          check-latest: true
          cache: true
        
    - name: Setup LLVM
      run: sudo apt install llvm-12

    - name: Get german locale
      run: sudo locale-gen de_DE.UTF-8
      if: runner.os == 'Linux'
        
    - name: Build
      run: make -j$(nproc)
      
    - name: Run tests
      run: make test
    
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: tests/coverage.md
        retention-days: 30

    - name: Build debug
      run: make -j$(nproc) debug
    
    - name: Run memory tests
      run: make test-memory
